[ERROR] 2018-09-23 14:28:29,956 | /home/vini/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-09-23 14:28:29.949564-192.168.85.168-889
